// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD40K8xnT1AG_Tjj1jik2v4g0oq-rv3Jg8',
    appId: '1:341612834236:web:a75c099e336de79abfcfb9',
    messagingSenderId: '341612834236',
    projectId: 'itemshop-b56a3',
    authDomain: 'itemshop-b56a3.firebaseapp.com',
    databaseURL: 'https://itemshop-b56a3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'itemshop-b56a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX4JOTG3wXMXauh6IXqVNIhu2lA943yr4',
    appId: '1:341612834236:android:4e79a95fa0461b49bfcfb9',
    messagingSenderId: '341612834236',
    projectId: 'itemshop-b56a3',
    databaseURL: 'https://itemshop-b56a3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'itemshop-b56a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRXUNjokku7VcssIeu8BL6Zyjgr8IK828',
    appId: '1:341612834236:ios:09a4212ab4813cf0bfcfb9',
    messagingSenderId: '341612834236',
    projectId: 'itemshop-b56a3',
    databaseURL: 'https://itemshop-b56a3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'itemshop-b56a3.appspot.com',
    iosBundleId: 'com.example.mistakeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRXUNjokku7VcssIeu8BL6Zyjgr8IK828',
    appId: '1:341612834236:ios:09a4212ab4813cf0bfcfb9',
    messagingSenderId: '341612834236',
    projectId: 'itemshop-b56a3',
    databaseURL: 'https://itemshop-b56a3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'itemshop-b56a3.appspot.com',
    iosBundleId: 'com.example.mistakeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD40K8xnT1AG_Tjj1jik2v4g0oq-rv3Jg8',
    appId: '1:341612834236:web:3459b906f49a445cbfcfb9',
    messagingSenderId: '341612834236',
    projectId: 'itemshop-b56a3',
    authDomain: 'itemshop-b56a3.firebaseapp.com',
    databaseURL: 'https://itemshop-b56a3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'itemshop-b56a3.appspot.com',
  );
}
